
##############################################################################
# MyCoRe Vue                                                                 #
##############################################################################

##############################################################################
# Pass Vue Properties                                                        #
##############################################################################
MCR.Vue.Properties=MCR.NameOfProject
