MCR.RestAPI.V2.Services=MCR.RestAPI.V2.Services.Class
MCR.URIResolver.ModuleResolver.checkrestapiaccess=MCR.URIResolver.ModuleResolver.checkrestapiaccess.Class
MCR.RestAPI.V2.AlternativeIdentifier.Objects.Keys=MCR.Object.IDMapper.ObjectSolrFields
MCR.RestAPI.V2.AlternativeIdentifier.Derivates.Keys=MCR.Object.IDMapper.DerivateSolrFields
