MCR.Viewer.bootstrapURL=MCR.Viewer.Bootstrap.Css.URL
MCR.Viewer.FontaweSomeURL=MCR.Viewer.Fontawesome.Css.URL
MCR.Viewer.configuration.strategy=MCR.Viewer.configuration.strategy.Class
MCR.Viewer.MCRIviewACLProvider=MCR.Viewer.MCRIviewACLProvider.Class
