MCR.user2.RoleCategegories=MCR.user2.RoleCategories
MCR.user2.HashIterations=MCR.User.PasswordCheck.Strategies.sha256.Iterations

MCR.URIResolver.ModuleResolver.user=MCR.URIResolver.ModuleResolver.user.Class
MCR.URIResolver.ModuleResolver.group=MCR.URIResolver.ModuleResolver.group.Class
MCR.URIResolver.ModuleResolver.realm=MCR.URIResolver.ModuleResolver.realm.Class
