MCR.URN.URNGranular.SupportedContentTypes=MCR.PI.URNGranular.SupportedContentTypes
MCR.URN.DNB.Credentials.Login=MCR.PI.DNB.Credentials.Login
MCR.URN.DNB.Credentials.Password=MCR.PI.DNB.Credentials.Password
MCR.PI.CronJob.disable=MCR.Cronjob.Jobs.DNBURNRegistrationCheck.Enabled
MCR.PI.GranularRESTRegistrationStarter.taskPeriod=MCR.Cronjob.Jobs.URNGranularRESTRegistration.Cron (and MCR.Cronjob.Jobs.URNGranularRESTRegistration.Class=org.mycore.pi.urn.rest.MCRURNGranularRESTRegistrationCronjob)
MCR.PI.GranularRESTRegistrationTask.batchSize=MCR.CronJob.Default.URNGranularRESTRegistration.BatchSize
MCR.PI.Generator.(\S+)=MCR.PI.Generator.$1.Class
MCR.PI.MetadataService.(\S+)=MCR.PI.MetadataService.$1.Class
MCR.PI.Service.(\S+)=MCR.PI.Service.$1.Class
