MCR.User.RestAPI.UserService.Class=org.mycore.user.restapi.v2.MCRUserService

##############################################################################
# REST API Resources                                                         #
##############################################################################
MCR.RestAPI.V2.Resource.Packages=%MCR.RestAPI.V2.Resource.Packages%,org.mycore.user.restapi.v2.resource
