##############################################################################
# REST API Resources                                                         #
##############################################################################
MCR.RestApi.Draft.MCRUsers=false
MCR.RestAPI.V2.Resource.Packages=%MCR.RestAPI.V2.Resource.Packages%,org.mycore.user.restapi.v2.resource
