MCR.OAIDataProvider.OAI2.EarliestDatestamp.fieldName=MCR.OAIDataProvider.OAI2.EarliestDatestamp.FieldName
MCR.OAIDataProvider.DefaultAdapter=MCR.OAIDataProvider.DefaultAdapter.Class
MCR.OAIDataProvider.DefaultSearcher=MCR.OAIDataProvider.DefaultSearcher.Class
MCR.OAIDataProvider.DefaultSetManager=MCR.OAIDataProvider.DefaultSetManager.Class
MCR.OAIDataProvider.(\S+).Adapter=MCR.OAIDataProvider.$1.Adapter.Class
MCR.OAIDataProvider.(\S+).Searcher=MCR.OAIDataProvider.$1.Searcher.Class
MCR.OAIDataProvider.(\S+).SetManager=MCR.OAIDataProvider.$1.SetManager.Class
