MCR.URIResolver.ModuleResolver.actionmapping=org.mycore.wfc.actionmapping.MCRActionMappingURIResolver
MCR.URIResolver.xslIncludes.functions=%MCR.URIResolver.xslIncludes.functions%,functions/actionmapping.xsl
