MCR.Editor.FileUpload.MaxSize=MCR.FileUpload.MaxSize
MCR.Editor.FileUpload.MemoryThreshold=MCR.FileUpload.MemoryThreshold
MCR.Editor.FileUpload.TempStoragePath=MCR.FileUpload.TempStoragePath
MCR.Filter.UserAgent=MCR.Filter.UserAgent.BotPattern

MCR.Jersey.resource.packages=MCR.Jersey.Resource.Packages
MCR.URN.Enabled.Objects=Your.Own.Property.see.MCR-1583

MCR.URIResolver.MaxObjectSize=MCR.HTTPClient.MaxObjectSize
MCR.URIResolver.MaxCacheEntries=MCR.HTTPClient.MaxCacheEntries
MCR.URIResolver.RequestTimeout=MCR.HTTPClient.RequestTimeout

MCR.Resource.Resolver.default.Provider.Class=MCR.Resource.Resolver.Providers.default.Class
MCR.Resource.Resolver.legacy.Provider.Class=MCR.Resource.Resolver.Providers.legacy.Class
MCR.Resource.Resolver.Provider=MCR.Resource.Resolver.SelectedProvider

MCR.Metadata.Manager=MCR.Metadata.Manager.Class

MCR.Persistence.Rule.Store_Class=MCR.Persistence.Rule.Store.Class

MCR.Category.DAO=MCR.Category.DAO.Class
MCR.Category.LinkService=MCR.Category.LinkService.Class
MCR.Jersey.Configuration=MCR.Jersey.Configuration.Class
MCR.Layout.Transformer.Factory=MCR.Layout.Transformer.Factory.Class
MCR.Metadata.Normalizer.(\S+).(\S+)=MCR.Metadata.Normalizer.$1.$2.Class
MCR.Metadata.Validator.(\S+).(\S+)=MCR.Metadata.Validator.$1.$2.Class
MCR.Access.Facts.Condition.(\S+)=MCR.Access.Facts.Condition.$1.Class
MCR.RuleParser.(\S+)=MCR.RuleParser.$1.Class

MCR.URIResolver.ModuleResolver.property=MCR.URIResolver.ModuleResolver.property.Class
MCR.URIResolver.ModuleResolver.callJava=MCR.URIResolver.ModuleResolver.callJava.Class
MCR.URIResolver.ModuleResolver.userobjectrights=MCR.URIResolver.ModuleResolver.userobjectrights.Class
MCR.URIResolver.ModuleResolver.staticcontent=MCR.URIResolver.ModuleResolver.staticcontent.Class
MCR.URIResolver.ModuleResolver.crypt=MCR.URIResolver.ModuleResolver.crypt.Class
MCR.URIResolver.ModuleResolver.ratelimit=MCR.URIResolver.ModuleResolver.ratelimit.Class

MCR.URIResolver.CachingResolver.Capacity=MCR.URIResolver.ModuleResolver.cache.CacheCapacity
MCR.URIResolver.CachingResolver.MaxAge=MCR.URIResolver.ModuleResolver.cache.CacheMaxAge

MCR.URIResolver.Classification.CacheSize=MCR.URIResolver.ModuleResolver.classification.CacheCapacity
MCR.URIResolver.Classification.Format.Text=MCR.URIResolver.ModuleResolver.classification.Format.Text
MCR.URIResolver.Classification.Format.Description=MCR.URIResolver.ModuleResolver.classification.Format.Description
MCR.URIResolver.Classification.Format.TextCounter=MCR.URIResolver.ModuleResolver.classification.Format.TextCounter
MCR.URIResolver.Classification.Format.IDText=MCR.URIResolver.ModuleResolver.classification.Format.IDText

MCR.URIResolver.XSLStyle.Flavor.xsl.TransformerFactoryClass=(MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xsl=org.mycore.common.xsl.uriresolver.MCRXSLStyleURIResolver$Flavor and MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xsl.TransformerFactory)
MCR.URIResolver.XSLStyle.Flavor.xsl.XSLFolder=MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xsl.XSLFolder
MCR.URIResolver.XSLStyle.Flavor.xslt.TransformerFactoryClass=(MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xsl=org.mycore.common.xslt.uriresolver.MCRXSLStyleURIResolver$Flavor and MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xslt.TransformerFactory)
MCR.URIResolver.XSLStyle.Flavor.xslt.XSLFolder=MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xslt.XSLFolder

MCR.Resource.Provider.Default.Caching.Coverage=MCR.Default.Resource.Provider.Caching.Coverage
MCR.Resource.Provider.Default.Caching.Capacity=MCR.Default.Resource.Provider.Caching.Capacity
MCR.Resource.Provider.Default.ClassLoader.Coverage=MCR.Default.Resource.Provider.ClassLoader.Coverage
MCR.Resource.Provider.Default.ClasspathDirs.Coverage=MCR.Default.Resource.Provider.ClasspathDirs.Coverage
MCR.Resource.Provider.Default.Combined.Coverage=MCR.Default.Resource.Provider.Combined.Coverage
MCR.Resource.Provider.Default.ConfigDirLibrary.Coverage=MCR.Default.Resource.Provider.ConfigDirLibrary.Coverage
MCR.Resource.Provider.Default.ConfigDirLibrary.Mode=MCR.Default.Resource.Provider.ConfigDirLibrary.Mode
MCR.Resource.Provider.Default.ConfigDir.Coverage=MCR.Default.Resource.Provider.ConfigDir.Coverage
MCR.Resource.Provider.Default.DeveloperOverride.Coverage=MCR.Default.Resource.Provider.DeveloperOverride.Coverage
MCR.Resource.Provider.Default.FileSystem.Coverage=MCR.Default.Resource.Provider.FileSystem.Coverage
MCR.Resource.Provider.Default.LFS.Coverage=MCR.Default.Resource.Provider.LFS.Coverage
MCR.Resource.Provider.Default.Library.Coverage=MCR.Default.Resource.Provider.Library.Coverage
MCR.Resource.Provider.Default.Observing.Coverage=MCR.Default.Resource.Provider.Observing.Coverage
MCR.Resource.Provider.Default.Synthetic.Coverage=MCR.Default.Resource.Provider.Synthetic.Coverage
MCR.Resource.Provider.Default.ServletContext.Coverage=MCR.Default.Resource.Provider.ServletContext.Coverage
MCR.Resource.Provider.Default.Web.Coverage=MCR.Default.Resource.Provider.Web.Coverage
MCR.Resource.Provider.Default.WebappClassesDir.Coverage=MCR.Default.Resource.Provider.WebappClassesDir.Coverage
MCR.Resource.Provider.Default.WebappDir.Coverage=MCR.Default.Resource.Provider.WebappDir.Coverage
MCR.Resource.Provider.Default.WebappLibrary.Coverage=MCR.Default.Resource.Provider.WebappLibrary.Coverage
MCR.Resource.Provider.Default.WebappLibrary.Mode=MCR.Default.Resource.Provider.WebappLibrary.Mode

MCR.Resource.Filter.Default.ConfigDirLibrary.Mode=MCR.Default.Resource.Filter.ConfigDirLibrary.Mode
MCR.Resource.Filter.Default.Library.Mode=MCR.Default.Resource.Filter.Library.Mode
MCR.Resource.Filter.Default.WebappLibrary.Mode=MCR.Default.Resource.Filter.WebappLibrary.Mode

