MCR.Editor.FileUpload.MaxSize=MCR.FileUpload.MaxSize
MCR.Editor.FileUpload.MemoryThreshold=MCR.FileUpload.MemoryThreshold
MCR.Editor.FileUpload.TempStoragePath=MCR.FileUpload.TempStoragePath
MCR.Filter.UserAgent=MCR.Filter.UserAgent.BotPattern

MCR.Jersey.resource.packages=MCR.Jersey.Resource.Packages
MCR.URN.Enabled.Objects=Your.Own.Property.see.MCR-1583

MCR.URIResolver.MaxObjectSize=MCR.HTTPClient.MaxObjectSize
MCR.URIResolver.MaxCacheEntries=MCR.HTTPClient.MaxCacheEntries
MCR.URIResolver.RequestTimeout=MCR.HTTPClient.RequestTimeout

MCR.Resource.Resolver.default.Provider.Class=MCR.Resource.Resolver.Providers.default.Class
MCR.Resource.Resolver.legacy.Provider.Class=MCR.Resource.Resolver.Providers.legacy.Class
MCR.Resource.Resolver.Provider=MCR.Resource.Resolver.SelectedProvider

MCR.Metadata.Manager=MCR.Metadata.Manager.Class

MCR.Persistence.Rule.Store_Class=MCR.Persistence.Rule.Store.Class

MCR.Category.DAO=MCR.Category.DAO.Class
MCR.Category.LinkService=MCR.Category.LinkService.Class
MCR.Jersey.Configuration=MCR.Jersey.Configuration.Class
MCR.Layout.Transformer.Factory=MCR.Layout.Transformer.Factory.Class
MCR.Metadata.Normalizer.(\S+).(\S+)=MCR.Metadata.Normalizer.$1.$2.Class
MCR.Metadata.Validator.(\S+).(\S+)=MCR.Metadata.Validator.$1.$2.Class
MCR.Access.Facts.Condition.(\S+)=MCR.Access.Facts.Condition.$1.Class
MCR.RuleParser.(\S+)=MCR.RuleParser.$1.Class

MCR.URIResolver.ModuleResolver.property=MCR.URIResolver.ModuleResolver.property.Class
MCR.URIResolver.ModuleResolver.callJava=MCR.URIResolver.ModuleResolver.callJava.Class
MCR.URIResolver.ModuleResolver.userobjectrights=MCR.URIResolver.ModuleResolver.userobjectrights.Class
MCR.URIResolver.ModuleResolver.staticcontent=MCR.URIResolver.ModuleResolver.staticcontent.Class
MCR.URIResolver.ModuleResolver.crypt=MCR.URIResolver.ModuleResolver.crypt.Class
MCR.URIResolver.ModuleResolver.ratelimit=MCR.URIResolver.ModuleResolver.ratelimit.Class

MCR.URIResolver.CachingResolver.Capacity=MCR.URIResolver.ModuleResolver.cache.CacheCapacity
MCR.URIResolver.CachingResolver.MaxAge=MCR.URIResolver.ModuleResolver.cache.CacheMaxAge

MCR.URIResolver.Classification.CacheSize=MCR.URIResolver.ModuleResolver.classification.CacheCapacity
MCR.URIResolver.Classification.Format.Text=MCR.URIResolver.ModuleResolver.classification.Format.Text
MCR.URIResolver.Classification.Format.Description=MCR.URIResolver.ModuleResolver.classification.Format.Description
MCR.URIResolver.Classification.Format.TextCounter=MCR.URIResolver.ModuleResolver.classification.Format.TextCounter
MCR.URIResolver.Classification.Format.IDText=MCR.URIResolver.ModuleResolver.classification.Format.IDText

MCR.URIResolver.XSLStyle.Flavor.xsl.TransformerFactoryClass=(MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xsl=org.mycore.common.xsl.uriresolver.MCRXSLStyleURIResolver$Flavor and MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xsl.TransformerFactory)
MCR.URIResolver.XSLStyle.Flavor.xsl.XSLFolder=MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xsl.XSLFolder
MCR.URIResolver.XSLStyle.Flavor.xslt.TransformerFactoryClass=(MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xsl=org.mycore.common.xslt.uriresolver.MCRXSLStyleURIResolver$Flavor and MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xslt.TransformerFactory)
MCR.URIResolver.XSLStyle.Flavor.xslt.XSLFolder=MCR.URIResolver.ModuleResolver.xslStyle.Flavor.xslt.XSLFolder
