MCR.Editor.FileUpload.MaxSize=MCR.FileUpload.MaxSize
MCR.Editor.FileUpload.MemoryThreshold=MCR.FileUpload.MemoryThreshold
MCR.Editor.FileUpload.TempStoragePath=MCR.FileUpload.TempStoragePath
MCR.Filter.UserAgent=MCR.Filter.UserAgent.BotPattern

MCR.Jersey.resource.packages=MCR.Jersey.Resource.Packages
MCR.URN.Enabled.Objects=Your.Own.Property.see.MCR-1583

MCR.URIResolver.MaxObjectSize=MCR.HTTPClient.MaxObjectSize
MCR.URIResolver.MaxCacheEntries=MCR.HTTPClient.MaxCacheEntries
MCR.URIResolver.RequestTimeout=MCR.HTTPClient.RequestTimeout

MCR.Resource.Resolver.default.Provider.Class=MCR.Resource.Resolver.Providers.default.Class
MCR.Resource.Resolver.legacy.Provider.Class=MCR.Resource.Resolver.Providers.legacy.Class
MCR.Resource.Resolver.Provider=MCR.Resource.Resolver.SelectedProvider

MCR.Metadata.Manager=MCR.Metadata.Manager.Class

MCR.Persistence.Rule.Store_Class=MCR.Persistence.Rule.Store.Class

MCR.Access.Facts.Condition.(\S+)=MCR.Access.Facts.Condition.$1.Class
MCR.Category.DAO=MCR.Category.DAO.Class
MCR.Category.LinkService=MCR.Category.LinkService.Class

MCR.Jersey.Configuration=MCR.Jersey.Configuration.Class
MCR.Layout.Transformer.Factory=MCR.Layout.Transformer.Factory.Class

MCR.Metadata.Normalizer.(\S+).(\S+)=MCR.Metadata.Normalizer.$1.$2.Class
MCR.Metadata.Validator.(\S+).(\S+)=MCR.Metadata.Validator.$1.$2.Class

MCR.RuleParser.(\S+)=MCR.RuleParser$1.Class
