/**
 * 
 * $Revision$ $Date$
 *
 * This file is part of ** M y C o R e **
 * Visit our homepage at http://www.mycore.de/ for details.
 *
 * This program is free software; you can use it, redistribute it
 * and / or modify it under the terms of the GNU General Public License
 * (GPL) as published by the Free Software Foundation; either version 2
 * of the License or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program, normally in the file license.txt.
 * If not, write to the Free Software Foundation Inc.,
 * 59 Temple Place - Suite 330, Boston, MA  02111-1307 USA
 *
 **/
package org.mycore.buildtools.anttasks;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.regex.Pattern;

import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.Task;
import org.mycore.buildtools.common.MCRSortedProperties;

/**
 * Ant task that allows 'mycore.properties' manipulation via ant.
 * 
 * @author Thomas Scheffler (yagee)
 */
public class MCRConfigurationTask extends Task {
    private static final Charset PROPERTY_CHARSET = Charset.forName("ISO-8859-1");

    // some constants
    private static final String MCR_CONFIGURATION_INCLUDE_DEFAULT = "MCR.Configuration.Include";

    private Pattern includePattern;

    // some fields setable and getable via methods
    private String action;

    private String key;

    private String value;

    private File propertyFile;

    private File mergeFile;

    // some fields needed for processing
    private boolean valuePresent = false;

    private boolean propertiesLoaded = false;

    private boolean fileChanged = false;

    private int lineNumber = -1;

    private ArrayList<String> propLines;

    /**
     * Execute the requested operation.
     * 
     * @throws BuildException
     *             if an error occurs
     */
    @Override
    public void execute() throws BuildException {
        checkPreConditions();
        if (action == null || action.length() == 0)
            action = "mergeFile";
        switch (action) {
            case "addInclude":
            case "removeInclude":
                loadLines();
                if (!propertiesLoaded) {
                    throw new BuildException("Could not load: " + propertyFile.getName());
                }
                if (action.equals("addInclude")) {
                    addInclude();
                } else if (action.equals("removeInclude")) {
                    removeInclude();
                }
                if (fileChanged) {
                    writeLines();
                }
                break;
            case "substituteVariables":
                throw new BuildException("action=\"substituteVariables\" is not supported anymore");
            default:
                try {
                    MCRSortedProperties orig = getProperties(propertyFile);
                    super.log("Merging property file: " + mergeFile);
                    orig.putAll(getProperties(mergeFile));
                    orig.remove("MCR.Configuration.Include");
                    try (FileOutputStream fout = new FileOutputStream(propertyFile)) {
                        orig.store(fout, "automatically generated by " + this.getClass().getName());
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    throw new BuildException("Error while merging properties.", e);
                }
                break;
        }
        reset();
    }

    private MCRSortedProperties getProperties(File pFile) throws FileNotFoundException, IOException {
        MCRSortedProperties returns = new MCRSortedProperties();
        if (pFile.exists()) {
            try (FileInputStream stream = new FileInputStream(pFile)) {
                returns.load(stream);
            }
        }
        return returns;
    }

    /**
     * checks whether all preconditions are met
     */
    private void checkPreConditions() throws BuildException {
        setIncludePattern(key);
        if (action == null && mergeFile == null) {
            throw new BuildException("Must specify 'action' attribute");
        }
        if (propertyFile == null) {
            throw new BuildException("Must specify 'propertyfile' attribute");
        }
        if (value == null && mergeFile == null && (action == null || !action.equals("substituteVariables"))) {
            throw new BuildException("Must specify 'value' attribute");
        }
        if (mergeFile == null
            && (action == null || !action.equals("addInclude") && !action.equals("removeInclude")
                && !action.equals("substituteVariables"))) {
            throw new BuildException("action must be either 'addInclude' or 'removeInclude'");
        }
        if (!propertyFile.exists() && mergeFile == null) {
            throw new BuildException(new FileNotFoundException(propertyFile + " does not exists."));
        }
        if (mergeFile != null && !mergeFile.exists()) {
            throw new BuildException(new FileNotFoundException(mergeFile + "does not exists."));
        }
    }

    /**
     * resets all local fields
     */
    private void reset() {
        action = null;
        key = null;
        propertyFile = null;
        mergeFile = null;
        lineNumber = -1;
        propertiesLoaded = false;
        fileChanged = false;
        valuePresent = false;
    }

    /**
     * adds an include
     */
    private void addInclude() {
        if (valuePresent) {
            handleOutput("Not changing " + propertyFile.getName() + ": '" + value + "' already included.");
            return;
        }
        fileChanged = true;
        String prop = propLines.get(lineNumber);
        String newProp = prop;
        if (prop.charAt(prop.length() - 1) != '=') {
            newProp += ",";
        }
        newProp += value;
        propLines.remove(lineNumber);
        propLines.add(lineNumber, newProp);
        handleOutput(propertyFile.getName() + ':' + lineNumber + " added '" + value + "' to " + getKey());
    }

    /**
     * removes an include
     */
    private void removeInclude() {
        if (!valuePresent) {
            handleOutput("Not changing " + propertyFile.getName() + ": '" + value + "' not present.");
            return;
        }
        fileChanged = true;
        String newProp = propLines.get(lineNumber).replaceAll("," + value, "");
        propLines.remove(lineNumber);
        propLines.add(lineNumber, newProp);
        handleOutput(propertyFile.getName() + ':' + lineNumber + " removed '" + value + "' from " + getKey());
    }

    /**
     * writes back the property file together with changed properties
     */
    private void writeLines() {
        BufferedWriter writer = null;
        try {
            writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(propertyFile), PROPERTY_CHARSET));
            for (Object element : propLines) {
                writer.write(element.toString());
                writer.newLine();
            }
        } catch (IOException e) {
            handleErrorOutput("Error while writing '" + propertyFile.getName() + "': " + e.getMessage());
        } finally {
            if (writer != null) {
                try {
                    writer.close();
                } catch (IOException e) {
                    handleErrorOutput("Error while closing file '" + propertyFile.getName() + "': " + e.getMessage());
                }
            }
        }
    }

    /*
     * loads the property file and marks the occurence of
     * MCR.Configuration.Include
     */
    private void loadLines() {
        BufferedReader reader = null;
        propertiesLoaded = false;
        try {
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(propertyFile), PROPERTY_CHARSET));
            propLines = new ArrayList<String>(1000);
            int i = 0;
            for (String line = reader.readLine(); line != null; line = reader.readLine()) {
                // add each line of the property file to the array list
                propLines.add(line);
                if (lineNumber < 0 && includePattern.matcher(line).find()) {
                    // found the MCR.Configuration.Include line
                    lineNumber = i;
                    if (line.indexOf(value) > 0) {
                        // value is included
                        valuePresent = true;
                    }
                }
                i++;
            }
            if (lineNumber < 0) {
                propLines.add(key + "=");
                lineNumber = propLines.size() - 1;
            }
            propertiesLoaded = true;
        } catch (IOException e) {
            handleErrorOutput("Error while reading '" + propertyFile.getName() + "': " + e.getMessage());
        } finally {
            try {
                if (reader != null) {
                    reader.close();
                }
            } catch (IOException e) {
                handleErrorOutput("Error while closing file '" + propertyFile.getName() + "': " + e.getMessage());
            }
        }
    }

    public String getAction() {
        return action;
    }

    /**
     * sets the action the task should perform.
     * 
     * @param action
     *            either "addInclude" or "removeInclude"
     */
    public void setAction(String action) {
        this.action = action;
    }

    public File getPropertyFile() {
        return propertyFile;
    }

    /**
     * sets the property file that needs to be changed.
     * 
     * @param propertyFile
     *            a 'mycore.properties' file
     */
    public void setPropertyFile(File propertyFile) {
        this.propertyFile = propertyFile;
    }

    public File getMergeFile() {
        return mergeFile;
    }

    public void setMergeFile(File mergeFile) {
        this.mergeFile = mergeFile;
    }

    public String getValue() {
        return value;
    }

    /**
     * sets the value for the action to be performed. For 'addInclude' a value
     * of "mycore.properties.moduleXY" would result in adding
     * ",mycore.properties.moduleXY" to the property
     * "MCR.Configuration.Include".
     * 
     * @param value
     *            a 'mycore.properties' file
     */
    public void setValue(String value) {
        this.value = value;
    }

    public String getKey() {
        if (key == null) {
            return MCR_CONFIGURATION_INCLUDE_DEFAULT;
        } else {
            return key;
        }
    }

    public void setKey(String key) {
        this.key = key;
    }

    public void setIncludePattern(String key) {
        if (key == null) {
            includePattern = Pattern.compile(MCR_CONFIGURATION_INCLUDE_DEFAULT);
        } else {
            includePattern = Pattern.compile(key);
        }
    }

}
