MCR.Jersey.Resource.Packages=%MCR.Jersey.Resource.Packages%,org.mycore.sass.resources

MCR.SASS.QuietDeps=true

# see https://sass-lang.com/documentation/js-api/interfaces/deprecations/
MCR.SASS.SilenceDeprecations=import
