{identifier:"id", label: 'name', items: [
	{id:"section", name:"Abschnitt"},
	{id:"annotation", name:"Annotation"},
	{id:"address", name:" Anrede"},
	{id:"article", name:"Artikel"},
	{id:"volume", name:"Band"},
	{id:"contained_work", name:"Beigefügtes oder Enthaltenes Werk"},
	{id:"additional", name:"Beilage"},
	{id:"provenance", name:"Besitznachweis"},
	{id:"collation", name:"Bogensignatur"},
	{id:"ornament", name:"Buchschmuck"},
	{id:"cover", name:"Deckel"},
	{id:"- cover_front", name:"- Vorderdeckel"},
	{id:"- cover_back", name:"- Rückdeckel"},
	{id:"printers_mark", name:"Druckermarke"},
	{id:"binding", name:"Einband"},
	{id:"entry", name:"Eintrag"},
	{id:"corrigenda", name:"Errata"},
	{id:"bookplate", name:"Exlibris"},
	{id:"fascicle", name:"Faszikel"},
	{id:"fragment", name:"Fragment"},
	{id:"manuscript", name:"Handschrift"},
	{id:"issue", name:"Heft"},
	{id:"illustration", name:" Illustration"},
	{id:"imprint", name:"Impressum"},
	{id:"contents", name:"Inhaltsverzeichnis"},
	{id:"initial_decoration", name:"Initialschmuck"},
	{id:"chapter", name:"Kapitel"},
	{id:"map", name:"Karte"},
	{id:"colophon", name:"Kolophon"},
	{id:"engraved_titlepage", name:"Kupfertitel"},
	{id:"multivolume_work", name:"Mehrbändiges Werk"},
	{id:"monograph", name:"Monographie"},
	{id:"musical_notation", name:"Musiknotation"},
	{id:"periodical", name:"Periodica"},
	{id:"privileges", name:"Privilegien"},
	{id:"index", name:"Register"},
	{id:"spine", name:"Rücken"},
	{id:"scheme", name:"Schema"},
	{id:"edge", name:"Schnitt"},
	{id:"paste_down", name:"Spiegel"},
	{id:"stamp", name:"Stempel"},
	{id:"table", name:"Tabelle"},
	{id:"text", name:"Text"},
	{id:"title_page", name:"Titelblatt"},
	{id:"verse", name:"Verse"},
	{id:"endsheet", name:"Vorsatz"},
	{id:"preface", name:"Vorwort"},
	{id:"dedication", name:"Widmung"}]
}                               