MCR.ORCID2.PreFillRegistrationForm=MCR.ORCID2.OAuth.PreFillRegistrationForm

MCR.URIResolver.ModuleResolver.hash=MCR.URIResolver.ModuleResolver.hash.Class
MCR.URIResolver.ModuleResolver.orcidCredential=MCR.URIResolver.ModuleResolver.orcidCredential.Class
