MCR.OCFL.Repository.Main=MCR.OCFL.Repository.Main.Class
MCR.Classification.Manager=MCR.Classification.Manager.Class
MCR.Content.DigestCalculator=MCR.Content.DigestCalculator.Class
MCR.Content.TransactionalStorage=MCR.Content.TransactionalStorage.Class
MCR.Content.RemoteStorage=MCR.Content.RemoteStorage.Class
MCR.Content.RemoteStorage.EvictionStrategy=MCR.Content.RemoteStorage.EvictionStrategy.Class
MCR.Cronjob.Jobs.CompactRemoteStorageJournal=MCR.Cronjob.Jobs.CompactRemoteStorageJournal.Class
